global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: node
    static_configs:
     - targets: ['89.208.199.170:9100']

  - job_name: 'golang'
    static_configs:
      - targets: ['89.208.199.170:8080']

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
